config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:details, :title, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
  <h2>Create or Edit Task</h2>
  <%= form_for(task) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :Done %>
      <%= f.check_box :completed, { class: 'form-control' }, true, false %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>Bienvenue, Florian</h1>

  <% @tasks.each do |task| %>
    <div class="link-to">
      <h2> <%= link_to task.title, task_path(task) %> </h2>
    </div>
    <p>
      <%= task.completed == true ? " 👍 " : " 👎 " %>
      <%= link_to task_path(task),
        method: :delete,
        data: { confirm: "Are you sure?" } do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </p>
  <% end %>
  <br>
  <div class="btn btn-outline-primary">
    <%= link_to 'Create task', tasks_new_path %>
  </div>
</div>
<!-- <i class="fas fa-trash-alt"></i> -->

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="container">
  <h2><%= @task.title %></h2>
  <br>

  <p><%= @task.details %></p>
  <br>

  <div class="link-to">
    <h4>
      <%= link_to edit_task_path(@task) do %>
      <i class="far fa-edit"></i>
      <% end %>
    </h4>
  </div>
  <br>

  <div class="btn btn-outline-primary">
    <%= link_to 'Back to list', tasks_path %>
  </div>
</div>